# add -Wall to try to catch everything we can.
EXTRA_CFLAGS += -Wall
EXTRA_CFLAGS += -I$(TOP)/kernel/motorola/modules/include \
		-I$(TOP)/kernel/motorola/modules/drivers/power/mmi_pl_chg_manager

obj-m += mmi_pl_chg_manager.o
