# add -Wall to try to catch everything we can.
EXTRA_CFLAGS += -Wall
EXTRA_CFLAGS += -I$(TOP)/kernel/motorola/modules/include \
		-I$(TOP)/kernel/motorola/modules/drivers/input/touchscreen/nova_36525_mmi

ifeq ($(filter m y, $(CONFIG_TOUCHSCREEN_NOVATEK_CHIPSET)),)
	obj-m := nova_36525_mmi.o
endif

nova_36525_mmi-objs += nt36xxx.o
nova_36525_mmi-objs += nt36xxx_ext_proc.o
nova_36525_mmi-objs += nt36xxx_fw_update.o
nova_36525_mmi-objs += nt36xxx_mp_ctrlram.o
